/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package processor;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Processor classUnderTest = new Processor();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.som());
    }
}
