name: Gradle Package

on:
  push:
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Grant execute permission for gradlew and refresh
      run: |
        chmod +x gradlew
        ./gradlew --refresh-dependencies
    - name: Build CommanDispatcher
      run: |
        ./gradlew commandDispatcher:build
        ./gradlew commanDispatcher:publishMavenJavaPublicationToMavenLocal
    - name: Build nukerbus
      run: |
        ./gradlew nukerbus:build
        ./gradlew nukerbus:publishMavenJavaPublicationToMavenLocal

    - name: Build processor
      run: |
        ./gradlew processor:build
        ./gradlew processor:publishMavenJavaPublicationToMavenLocal

    - name: Build Oragehack
      run: |
        ./gradlew oragehack:build

    - name: List files
      run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Oragehack
        path: ./oragehack/build/libs/oragehack*.jar 

